# ==========================================
# Tata 1mg NVR Security Operations Center
# Enterprise Configuration
# ==========================================

ORGANIZATION_NAME = "Tata 1mg"

SYSTEM_NAME = "NVR Security Operations Center"

APPLICATION_NAME = f"{ORGANIZATION_NAME} {SYSTEM_NAME}"

# ==========================================
# Dashboard Settings
# ==========================================

AUTO_REFRESH_SECONDS = 5

POLLING_INTERVAL = 5

ALERT_DELAY_SECONDS = 15

ENABLE_DUPLICATE_PROTECTION = True

# ==========================================
# Email Branding
# ==========================================

EMAIL_BRAND = APPLICATION_NAME

EMAIL_FOOTER = (
    "This is an automated alert generated by "
    "Tata 1mg NVR Security Operations Center."
)

# ==========================================
# Dashboard
# ==========================================

CAMERAS_PER_PAGE = 25

DEFAULT_SORT = "camera"

DEFAULT_STATUS_FILTER = "ALL"

# ==========================================
# Alert Colors
# ==========================================

STATUS_ONLINE = "Online"

STATUS_OFFLINE = "Offline"

COLOR_ONLINE = "#22C55E"

COLOR_OFFLINE = "#EF4444"

COLOR_WARNING = "#F59E0B"

# ==========================================
# Hikvision NVR Configuration
# ==========================================

NVRS = [
    {
        "id": 1,
        "name": "NVR-1",
        "ip": "192.168.1.6",
        "port": 85,
        "username": "admin",
        "password": "Stark@#$24",
    },
    {
        "id": 2,
        "name": "NVR-2",
        "ip": "192.168.1.7",
        "port": 84,
        "username": "admin",
        "password": "Stark@#$24",
    },
    {
        "id": 3,
        "name": "NVR-3",
        "ip": "192.168.1.5",
        "port": 82,
        "username": "admin",
        "password": "Stark@#$24",
    },
    {
        "id": 4,
        "name": "NVR-4",
        "ip": "192.168.1.4",
        "port": 81,
        "username": "admin",
        "password": "Stark@#$24",
    },
    {
        "id": 5,
        "name": "NVR-5",
        "ip": "192.168.1.3",
        "port": 83,
        "username": "admin",
        "password": "Stark@#$24",
    }
]