# ==========================================================
# VisionGuard AI Enterprise Configuration
# Tata 1mg - NVR Security Operations Center
# ==========================================================

# ==========================================================
# Organization
# ==========================================================

ORGANIZATION_NAME = "Tata 1mg"

SYSTEM_NAME = "NVR Security Operations Center"

APPLICATION_NAME = f"{ORGANIZATION_NAME} {SYSTEM_NAME}"

APPLICATION_VERSION = "3.0 Enterprise"

# ==========================================================
# Dashboard Configuration
# ==========================================================

AUTO_REFRESH_SECONDS = 5

POLLING_INTERVAL = 5

ALERT_DELAY_SECONDS = 15

CAMERAS_PER_PAGE = 25

DEFAULT_SORT = "camera"

DEFAULT_STATUS_FILTER = "ALL"

ENABLE_DUPLICATE_PROTECTION = True

# ==========================================================
# Email Configuration
# ==========================================================

EMAIL_ALERT_ENABLED = True

EMAIL_BRAND = APPLICATION_NAME

EMAIL_FOOTER = (
    "This is an automated alert generated by "
    "VisionGuard AI Enterprise Monitoring Platform."
)

EMAIL_COOLDOWN_MINUTES = 15

ENABLE_EMAIL_LOGGING = True

MAX_EMAIL_RETRY = 3

SMTP_TIMEOUT = 15
MAX_EMAIL_RETRY = 3

SMTP_TIMEOUT = 15

# ==========================================================
# SMTP Configuration
# ==========================================================

SMTP_SERVER = "smtp.gmail.com"

SMTP_PORT = 587

SMTP_USERNAME = "zubair.khan@1mg.com"

SMTP_PASSWORD = "garajkqynquqccpe"

RECEIVER_EMAIL = "zubair.khan@1mg.com"

# ==========================================================
# Alert Configuration
# ==========================================================

ENABLE_CAMERA_OFFLINE_ALERT = True

# ==========================================================
# Alert Configuration
# ==========================================================

ENABLE_CAMERA_OFFLINE_ALERT = True

ENABLE_CAMERA_RECOVERY_ALERT = True

ENABLE_IDENTITY_ALERT = True

ENABLE_IP_CONFLICT_ALERT = True

ENABLE_IP_CONFLICT_RECOVERY = True

ENABLE_VIDEO_LOSS_ALERT = True

ENABLE_STORAGE_FAILURE_ALERT = True

ENABLE_NETWORK_ALERT = True

ENABLE_POWER_FAILURE_ALERT = True

ENABLE_CAMERA_TAMPERING_ALERT = True

ENABLE_ANALYTICS_REPORT = True

# ==========================================================
# Dashboard Status
# ==========================================================

STATUS_ONLINE = "Online"

STATUS_OFFLINE = "Offline"

STATUS_WARNING = "Warning"

STATUS_UNKNOWN = "Unknown"

# ==========================================================
# UI Colors
# ==========================================================

COLOR_ONLINE = "#22C55E"

COLOR_OFFLINE = "#EF4444"

COLOR_WARNING = "#F59E0B"

COLOR_INFO = "#2563EB"

COLOR_CRITICAL = "#DC2626"

# ==========================================================
# Hikvision NVR Configuration
# ==========================================================

NVRS = [

    {
        "id": 1,
        "name": "NVR-1",
        "ip": "192.168.1.6",
        "port": 85,
        "username": "admin",
        "password": "Stark@#$24",
    },

    {
        "id": 2,
        "name": "NVR-2",
        "ip": "192.168.1.7",
        "port": 84,
        "username": "admin",
        "password": "Stark@#$24",
    },

    {
        "id": 3,
        "name": "NVR-3",
        "ip": "192.168.1.5",
        "port": 82,
        "username": "admin",
        "password": "Stark@#$24",
    },

    {
        "id": 4,
        "name": "NVR-4",
        "ip": "192.168.1.4",
        "port": 81,
        "username": "admin",
        "password": "Stark@#$24",
    },

    {
        "id": 5,
        "name": "NVR-5",
        "ip": "192.168.1.3",
        "port": 83,
        "username": "admin",
        "password": "Stark@#$24",
    }

]

# ==========================================================
# Future Enterprise Features
# ==========================================================

SUPPORTED_ALERTS = [

    "Camera Offline",

    "Camera Recovery",

    "Identity Changed",

    "IP Conflict",

    "IP Conflict Resolved",

    "Video Loss",

    "Storage Failure",

    "Network Issue",

    "Power Failure",

    "Camera Tampering",

    "Analytics Report"

]

# ==========================================================
# End of Configuration
# ==========================================================